baseURL: "https://siqiqu.github.io/"
title: Siqi Qu
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

pagination:
  pagerSize: 20

taxonomies:
  tag: tags

menu:
  main:
    - name: Publications
      url: papers/
      weight: 1
    - name: Conferences&Talks
      url: data/
      weight: 2
    - name: Courses
      url: courses/
      weight: 3

params:

  description: "Siqi Qu - Ph.D. student in Mathematics at the University of Mannheim & University of Groningen."
  author: Siqi Qu

  DateFormat: "January 2006"
  defaultTheme: light
  hideFooter: true
  disableThemeToggle: true

  ShowShareButtons: false
  ShowReadingTime: false
  disableSpecial1stPost: true
  disableAnchoredHeadings: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowAllPagesInArchive: false

  MainSections:
    - courses
    - papers
    - news

  ShowToc: false
  disableScrollToTop: true
  TocOpen: true
  ShowWordCount: false
  UseHugoToc: true
  comments: false
  math: true

  # 主题相关配置（必须在 params 里面）
  assets:
    disableScrollBarStyle: true
    customCSS:
      - css/custom.css

  cover:
    hiddenInList: false
    hiddenInSingle: true

  label:
    text: "Siqi Qu"
    iconHeight: 18

  profileMode:
    enabled: true
    title: Siqi Qu
    subtitle: |
      <p>
      Hello! I am a 4th year Ph.D. student in Mathematics pursuing a double degree at the University of Mannheim and the University of Groningen.
      </p><br>
      <p>
      My research lies at the intersection of optimization, variational analysis, and dynamical systems. I study constrained variational inequalities and monotone inclusion problems in Hilbert spaces.
      </p><br>
      <p>
      A central theme of my work is the design and analysis of dynamical systems incorporating penalization and Tikhonov regularization to ensure strong convergence toward least-norm solutions.
      </p>
    imageUrl: "siqiweb.jpeg"
    imageWidth: 160
    imageHeight: 160
    buttons:
      - name: Publications
        url: papers/
      - name: Conferences&Talks
        url: data/
      - name: Courses
        url: courses/

  socialIcons:
    - name: Email
      url: mailto:qu.siqi@uni-mannheim.de
    - name: ORCID
      url: https://orcid.org/0000-0002-0313-4851
    - name: LinkedIn
      url: https://www.linkedin.com/in/siqi-qu-581b12371/

markup:
  goldmark:
    renderer:
      unsafe: true

  highlight:
    guessSyntax: true
    style: autumn

  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2
